intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../../include/libdcore/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{dcore}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{dcore}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmia obja}{*}: cxx.poptions += -DLIBDCORE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBDCORE_SHARED_BUILD

# Export options.
#
lib{dcore}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{dcore}: cxx.export.poptions += -DLIBDCORE_STATIC
libs{dcore}: cxx.export.poptions += -DLIBDCORE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{dcore}: bin.lib.version = "-$version.project_id"
else
  lib{dcore}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
